const db = require('./models/database.js');

class DBActions {

  // TODO how do we make sure this query happens before any future ones?
  constructor() {
    const createTable =
      `CREATE TABLE IF NOT EXISTS Links (
          link_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          link_code char(6),
          state text NOT NULL,
          date_created timestamp not null default CURRENT_TIMESTAMP
        )`;

    db.query(createTable, [], (err, res) => {
      console.log(err ? err.stack : res);
    })
  }


  addRow(obj, cb) {
    db.query(
      'INSERT INTO Links (link_code, state) VALUES ($1, $2)', 
      [ obj.link_code, obj.state ],
      (err, dbRes) => {
        if (err) { console.log(err); return (err); }
        cb(obj);
      });
  }

  findByLinkCode(link_code, cb) {
    db.query(
      `SELECT * FROM Links WHERE link_code = '${link_code}'`, 
      [], 
      (err, dbRes) => {
        if (err) { throw err; }
        cb(dbRes);
      });
  }
}

module.exports = { DBActions };