#!/usr/bin/env node
const express = require('express');
const path = require('path');
const app = express();

require('dotenv').config()
const {PORT} = process.env;

app.use(express.static(path.join(__dirname, 'build')));

app.get('/', function (req, res) {
  res.sendFile(path.join(__dirname, 'build', 'index.html'));
});

app.listen(PORT, () => {
  if (!PORT) { console.error ('.env file is missing.')}
  console.log(`Listening on port ${PORT}`);
})